<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Msisdn Verify</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body>

  <form method="POST" action="/login.php">

    <div><input type="input" name="username" placeholder="Username"></div>
    <div><input type="password" name="password"></div>
    <div><input type="submit" value="Login"></div>
  </form>
    

</body>
